/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package py.edu.fiuni.vista.gamestore;

import javax.swing.JOptionPane;


/**
 *
 * @author HP
 */
public class Logueo extends javax.swing.JFrame {

    /**
     * Creates new form Logueo
     */
    public Logueo() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        password = new javax.swing.JPasswordField();
        usuario = new javax.swing.JLabel();
        contra = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        accesoSistema = new javax.swing.JLabel();
        ingresar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        password.setForeground(new java.awt.Color(153, 153, 153));
        password.setBorder(null);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, 180, 30));

        usuario.setBackground(new java.awt.Color(255, 255, 255));
        usuario.setFont(new java.awt.Font("Corbel Light", 0, 24)); // NOI18N
        usuario.setForeground(new java.awt.Color(238, 112, 82));
        usuario.setText("Usuario: ");
        usuario.setAutoscrolls(true);
        usuario.setName(""); // NOI18N
        usuario.setOpaque(true);
        jPanel1.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 100, 30));

        contra.setBackground(new java.awt.Color(255, 255, 255));
        contra.setFont(new java.awt.Font("Corbel Light", 0, 24)); // NOI18N
        contra.setForeground(new java.awt.Color(238, 112, 82));
        contra.setText("Contraseña: ");
        contra.setOpaque(true);
        jPanel1.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 120, -1));

        txtusuario.setForeground(new java.awt.Color(153, 153, 153));
        txtusuario.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtusuario.setBorder(null);
        txtusuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 180, 30));

        accesoSistema.setBackground(new java.awt.Color(255, 255, 255));
        accesoSistema.setFont(new java.awt.Font("Corbel Light", 0, 36)); // NOI18N
        accesoSistema.setForeground(new java.awt.Color(238, 112, 82));
        accesoSistema.setText("Acceso al Sistema");
        accesoSistema.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        accesoSistema.setOpaque(true);
        jPanel1.add(accesoSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesParaElProyecto/Enter_OFF.png"))); // NOI18N
        ingresar.setBorder(null);
        ingresar.setBorderPainted(false);
        ingresar.setContentAreaFilled(false);
        ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesParaElProyecto/Enter_ON.png"))); // NOI18N
        ingresar.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesParaElProyecto/Enter_ON.png"))); // NOI18N
        ingresar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesParaElProyecto/Enter_ON.png"))); // NOI18N
        ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ingresarMouseClicked(evt);
            }
        });
        jPanel1.add(ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 90, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 210, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 210, 20));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesParaElProyecto/icons8_customer_32px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesParaElProyecto/icons8_Key_32px.png"))); // NOI18N
        jLabel2.setText("jLabel1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 30, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 311));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuarioActionPerformed

    private void ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingresarMouseClicked
        String usuario = "admin";
        String contra = "havit";

        String pass = new String(password.getPassword());
        if (txtusuario.getText().equals(usuario) && pass.equals(contra)) {
            formPrincipal tienda = new formPrincipal();
            tienda.setVisible(true);
            dispose();
        } else {
            JOptionPane.showInternalMessageDialog(null, "Contrasena incorrecta!!");
            txtusuario.setText("");
            password.setText("");
        }
    }//GEN-LAST:event_ingresarMouseClicked

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logueo.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logueo.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logueo.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logueo.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logueo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accesoSistema;
    private javax.swing.JLabel contra;
    private javax.swing.JButton ingresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txtusuario;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
